# Generated by Django 2.0.4 on 2018-04-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=265, null=True)),
                ('nucleotide_change', models.CharField(max_length=265, null=True)),
                ('protein_change', models.CharField(max_length=265, null=True)),
                ('other_mappings', models.CharField(max_length=500, null=True)),
                ('alias', models.CharField(max_length=265, null=True)),
                ('transcripts', models.CharField(max_length=265, null=True)),
                ('region', models.CharField(max_length=265, null=True)),
                ('reported_classification', models.CharField(max_length=265, null=True)),
                ('inferred_classification', models.CharField(max_length=265, null=True)),
                ('source', models.CharField(max_length=265, null=True)),
                ('last_evaluated', models.DateField(null=True)),
                ('last_updated', models.DateField(null=True)),
                ('url', models.URLField()),
                ('submitter_comment', models.CharField(max_length=265, null=True)),
                ('assembly', models.CharField(max_length=265, null=True)),
                ('char', models.CharField(max_length=265, null=True)),
                ('genomic_start', models.IntegerField()),
                ('genomic_stop', models.IntegerField()),
                ('ref', models.CharField(max_length=265, null=True)),
                ('alt', models.CharField(max_length=265, null=True)),
                ('accession', models.CharField(max_length=265, null=True)),
                ('reported_ref', models.CharField(max_length=265, null=True)),
                ('reported_alt', models.CharField(max_length=265, null=True)),
            ],
        ),
    ]
