# Generated by Django 2.0.4 on 2018-04-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='genomic_start',
            field=models.CharField(max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='genomic_stop',
            field=models.CharField(max_length=265, null=True),
        ),
    ]
