# Generated by Django 2.0.4 on 2018-04-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_app', '0002_auto_20180411_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='other_mappings',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
