# Generated by Django 2.0.4 on 2018-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_app', '0004_auto_20180411_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='submitter_comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
