# Generated by Django 2.0.4 on 2018-04-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_app', '0005_auto_20180411_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='other_mappings',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
